[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scnf"
version = "0.1.0"
description = "A pyhon package for Steerable Continuous Normalizing Flows"
authors = [
    {name = "Rodrigo Voivodic", email = "rodrigo.voivodic@gmail.com"}
]
dependencies = [
    "equinox",
    "diffrax",
    "jaxtyping",
    "optax",
    "e3nn_jax",
    "h5py",
]

[tool.setuptools]
packages = ["scnf"]
